version: '3.8'
services:
  mariadb:
    image: mariadb:11.8.2
    container_name: basura_cero_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - basura_cero_mariadb:/var/lib/mysql

volumes:
  basura_cero_mariadb:
